config = {
    "vendor": "PostgreSQL",
    "cnx_path": "./cnx.ini",
    "language": "en",
    "ddl_path": "./ddl.sql",
    "dataset_dir": "../dataset",
    "source_path": "./sql_island.ipynb",
    "output_dir": "./output",
    "reformat_sql": False,
    "info": {
        "description": "An SQLab adaptation of SQL Island under PostgreSQL.",
        "version": "1.2.0",
        "repository": "https://github.com/laowantong/sqlab_island",
        "license": "https://creativecommons.org/licenses/by-sa/4.0/",
        "author_name": "Aristide Grange",
        "author_affiliation": "LCOMS, Université de Lorraine, France",
        "author_contact": "first_name.last_name at univ-lorraine.fr",
        "author_role": "Adaptation for SQLab",
        "original_author_name": "Johannes Schildgen",
        "original_author_affiliation": "Ostbayerische Technische Hochschule (OTH) Regensburg, Germany",
        "original_author_contact": "https://www.johannesschildgen.de",
        "original_author_role": "Dataset and storyline creation",
        "original_repository": "https://github.com/jschildgen/sql-island",
        "original_license": "MIT",
        "original_dbms": "SQLite",
    },
}
