DROP TABLE IF EXISTS inhabitant;
CREATE TABLE inhabitant (
  personid INTEGER NOT NULL PRIMARY KEY,
  name TEXT DEFAULT NULL,
  villageid INTEGER DEFAULT NULL,
  gender TEXT DEFAULT NULL,
  job TEXT DEFAULT NULL,
  gold INTEGER DEFAULT NULL,
  state TEXT DEFAULT NULL,
  hash INTEGER
);

DROP TABLE IF EXISTS item;
CREATE TABLE item (
  item TEXT NOT NULL PRIMARY KEY,
  owner INTEGER DEFAULT NULL,
  hash INTEGER,
  FOREIGN KEY (owner) REFERENCES inhabitant (personid) ON DELETE SET NULL
);

DROP TABLE IF EXISTS village;
CREATE TABLE village (
  villageid INTEGER NOT NULL PRIMARY KEY,
  name TEXT DEFAULT NULL,
  chief INTEGER DEFAULT NULL,
  hash INTEGER,
  FOREIGN KEY (chief) REFERENCES inhabitant (personid)
);
